# Generated by Django 2.2.14 on 2020-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter song title', max_length=30)),
                ('creator', models.CharField(help_text='<a href="https://www.kevin.com/musicmachine/creators/creator_id">Creator profile</a>', max_length=16, verbose_name='Creator')),
                ('tempo', models.IntegerField(max_length=3, verbose_name='Tempo')),
                ('summary', models.TextField(help_text='Enter a brief description of the song', max_length=1000)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['creator', 'title'],
            },
        ),
    ]
